name: Matrix Demo
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest,macos-latest]
        python-version: [3.8,3.9,3.10]
    steps:
      - name: Print version
        run: echo "Python $ {{matrix.python-version}}"