name: Matrix Demo 
on: push   #trigger 
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest,window-latest]
        python-version: [3.8,3.9,3.10]
    steps:
      - name: print version
        run: echo "python $ {{matrix.python.version}}"